name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add SSH Key and Disable Host Key Checking
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate || . venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-app
            sudo systemctl restart nginx
          EOF
