name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Server IP
      run: |
        echo "Server IP: ${{ secrets.SERVER_IP }}"

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/hng12-fastapi-key.pem
        chmod 600 ~/.ssh/hng12-fastapi-key.pem

    - name: SSH Debug
      run: ssh -vvv -i ~/.ssh/hng12-fastapi-key.pem ubuntu@${{ secrets.SERVER_IP }} -p 22

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key_path: "~/.ssh/hng12-fastapi-key.pem"
        port: 22
        script: |
          cd ~/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
